[package]
name = "sus"
version = "0.0.0"
edition = "2021"

[[bin]]
name = "sus-kernel"

[dependencies]
nix = "0.23.0"
serde = { version="1.0.130", features = ["derive"] }
serde_json = "1.0.67"
users = "0.11.0"